# GERADO por tools/theme-sync.py a partir do Theme.qml. NAO EDITE.

background            #1c1a17
foreground            #e8dcc0
selection_background  #241a12
selection_foreground  #f1ead9
cursor                #c9a24a
cursor_text_color     #1c1a17
url_color             #e3c37a

tab_bar_background       #0a0908
active_tab_foreground    #0a0908
active_tab_background    #c9a24a
inactive_tab_foreground  #6d6a63
inactive_tab_background  #201a14

color0  #0a0908
color1  #9f6460
color2  #b1a996
color3  #c9a24a
color4  #6d6a63
color5  #8b6bd9
color6  #56544e
color7  #e8dcc0
color8  #44423d
color9  #a06237
color10 #e8dcc0
color11 #e3c37a
color12 #b1a996
color13 #ac93d0
color14 #6d6a63
color15 #f1ead9
